desc "Compiles all .less files in css/src into css/*.css files"

task :default do
 require 'less'

 src_dest = './'
 dest = '../'
 files = Dir.entries(src_dest)

 files.select{|s| File.extname(s) == ".less"}.each do |sheet|
    f = File.new("#{dest}#{File.basename(sheet, ".less")}.css", File::CREAT|File::TRUNC|File::RDWR, 0644)
      f.write Less::Engine.new(File.new(src_dest + sheet)).to_css
 end
end
